<a href="https://colab.research.google.com/github/HanzlaJavaid/Algorithms/blob/master/ANN_META.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import random
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow_datasets as tfds
import pandas as pd
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split

In [ ]:
u0_df = pd.read_csv("/content/drive/MyDrive/Dataset/user_a.csv")
u0_df["user"] = 0
u1_df = pd.read_csv("/content/drive/MyDrive/Dataset/user_b.csv")
u1_df["user"] = 1
u2_df = pd.read_csv("/content/drive/MyDrive/Dataset/user_c.csv")
u2_df["user"] = 2
u3_df = pd.read_csv("/content/drive/MyDrive/Dataset/user_d.csv")
u3_df["user"] = 3

In [ ]:
collective_df = pd.concat([u0_df,u1_df,u2_df,u3_df])

In [ ]:
collective_df.head()

Class  AF3 delta std  AF3 delta m  ...  AF4 beta std  AF4 beta m  user
0    1.0    3569.164550  2063.892754  ...     46.280843   73.565719     0
1    1.0    3568.423670  2063.099248  ...     38.559351   67.470041     0
2    1.0    3568.157929  2062.445859  ...     43.210004   67.781924     0
3    1.0    3567.710021  2062.112673  ...     39.250246   65.031031     0
4    1.0    3565.546124  2063.128867  ...     33.901687   66.956313     0

[5 rows x 114 columns]

In [ ]:
collective_df["actual_class"] = collective_df["Class"].astype(str) + "_" + collective_df["user"].astype(str)

In [ ]:
collective_df.drop(["Class"],inplace=True,axis = 1)

In [ ]:
genarlization_df =collective_df.loc[collective_df["user"] == 1]

In [ ]:
train_df = collective_df.loc[collective_df["user"] != 1]
#ds_train,ds_test,_,_ = train_test_split(train_df.values[:,1:],train_df.values[:,-1],test_size=0.2)

In [ ]:
train_df.drop(["user"],axis=1,inplace=True)
genarlization_df.drop(["user"],axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
genarlization_arr = genarlization_df.values[:,:]

In [ ]:
ds_train,ds_test,_,_ = train_test_split(train_df.values[:,:],train_df.values[:,-1],test_size=0.1)

In [ ]:
ds_train.shape

(7776, 113)

In [ ]:
learning_rate = 0.001
meta_step_size = 0.10

inner_batch_size = 25
eval_batch_size = 25

meta_iters = 3000
eval_iters = 10
inner_iters = 10

eval_interval = 250
train_shots = 30
shots = 30
classes = 3

In [ ]:
class Dataset:
  def __init__(self,training,gen_test=False):
    if training:
      ds = ds_train
    else:
      ds = ds_test

    if gen_test:
      ds = genarlization_arr

    x = ds[:,:-1]
    y = ds[:,-1]

    scaler = MinMaxScaler()
    x = scaler.fit_transform(x)

    dataset = tf.data.Dataset.from_tensor_slices((x,y))

    self.data = {}

    for img,label in dataset:
      image = img.numpy()
      lab = str(label.numpy().decode("utf-8"))
      if lab not in self.data:
        self.data[lab] = []
      self.data[lab].append(image)
    self.labels = list(self.data.keys())

  def get_mini_dataset(self, batch_size, repetitions, shots, num_classes, split=False):
        temp_labels = np.zeros(shape=(num_classes * shots))
        temp_images = np.zeros(shape=(num_classes * shots, 112))
        if split:
            test_labels = np.zeros(shape=(num_classes))
            test_images = np.zeros(shape=(num_classes, 112))

        label_subset = random.choices(self.labels, k=num_classes)
        for class_idx, class_obj in enumerate(label_subset):
          
            temp_labels[class_idx * shots : (class_idx + 1) * shots] = class_idx
            
            if split:
                test_labels[class_idx] = class_idx
                images_to_split = random.choices(
                    self.data[label_subset[class_idx]], k=shots + 1
                )
                test_images[class_idx] = images_to_split[-1]
                temp_images[
                    class_idx * shots : (class_idx + 1) * shots
                ] = images_to_split[:-1]
            else:
               
                temp_images[
                    class_idx * shots : (class_idx + 1) * shots
                ] = random.choices(self.data[label_subset[class_idx]], k=shots)

        dataset = tf.data.Dataset.from_tensor_slices(
            (temp_images.astype(np.float32), temp_labels.astype(np.int32))
        )
        dataset = dataset.shuffle(100).batch(batch_size).repeat(repetitions)
        if split:
            return dataset, test_images, test_labels
        return dataset

In [ ]:
train_dataset = Dataset(training=True)
test_dataset = Dataset(training=False)

In [ ]:
def ann_bn(x,n):
    x = layers.Dense(n)(x)
    x = layers.BatchNormalization()(x)
    return layers.ReLU()(x)

def dropout_layer(x,n):
    return layers.Dropout(0.3)

inputs = layers.Input(shape=(112,))
x = ann_bn(inputs,512)
x = ann_bn(x,768)
x = ann_bn(x,1024)
x = ann_bn(x,512)
x = ann_bn(x,64)
outputs = layers.Dense(classes, activation="softmax")(x)
model = keras.Model(inputs=inputs, outputs=outputs)
model.compile()
optimizer = keras.optimizers.SGD(learning_rate=learning_rate)

In [ ]:
training = []
testing = []
for meta_iter in range(meta_iters):
    frac_done = meta_iter / meta_iters
    cur_meta_step_size = (1 - frac_done) * meta_step_size
    # Temporarily save the weights from the model.
    old_vars = model.get_weights()
    # Get a sample from the full dataset.
    mini_dataset = train_dataset.get_mini_dataset(
        inner_batch_size, inner_iters, train_shots, classes
    )
    for images, labels in mini_dataset:
        with tf.GradientTape() as tape:
            preds = model(images)
            loss = keras.losses.sparse_categorical_crossentropy(labels, preds)
        grads = tape.gradient(loss, model.trainable_weights)
        optimizer.apply_gradients(zip(grads, model.trainable_weights))
    new_vars = model.get_weights()
    # Perform SGD for the meta step.
    for var in range(len(new_vars)):
        new_vars[var] = old_vars[var] + (
            (new_vars[var] - old_vars[var]) * cur_meta_step_size
        )
    # After the meta-learning step, reload the newly-trained weights into the model.
    model.set_weights(new_vars)
    # Evaluation loop
    if meta_iter % eval_interval == 0:
        accuracies = []
        for dataset in (train_dataset, test_dataset):
            # Sample a mini dataset from the full dataset.
            train_set, test_images, test_labels = dataset.get_mini_dataset(
                eval_batch_size, eval_iters, shots, classes, split=True
            )
            old_vars = model.get_weights()
            # Train on the samples and get the resulting accuracies.
            for images, labels in train_set:
                with tf.GradientTape() as tape:
                    preds = model(images)
                    loss = keras.losses.sparse_categorical_crossentropy(labels, preds)
                grads = tape.gradient(loss, model.trainable_weights)
                optimizer.apply_gradients(zip(grads, model.trainable_weights))
            test_preds = model.predict(test_images)
            test_preds = tf.argmax(test_preds).numpy()
            num_correct = (test_preds == test_labels).sum()
            # Reset the weights after getting the evaluation accuracies.
            model.set_weights(old_vars)
            accuracies.append(num_correct / classes)
        training.append(accuracies[0])
        testing.append(accuracies[1])
        if meta_iter % 100 == 0:
            print(
                "batch %d: train=%f test=%f" % (meta_iter, accuracies[0], accuracies[1])
            )

batch 0: train=0.666667 test=1.000000
batch 500: train=1.000000 test=1.000000
batch 1000: train=0.333333 test=0.333333
batch 1500: train=1.000000 test=0.333333
batch 2000: train=1.000000 test=0.333333
batch 2500: train=1.000000 test=0.333333


In [ ]:
from sklearn.metrics import accuracy_score
def test_generalization(n):
    gen_accuracy = []
    gen_dataset = Dataset(training=False,gen_test=True) 
    for i in range (0,n):
      train_set, test_images, test_labels = gen_dataset.get_mini_dataset(eval_batch_size, eval_iters, shots, classes, split=True)
      for images, labels in train_set:
        with tf.GradientTape() as tape:
            preds = model(images)
            loss = keras.losses.sparse_categorical_crossentropy(labels, preds)
        grads = tape.gradient(loss, model.trainable_weights)
        optimizer.apply_gradients(zip(grads, model.trainable_weights))
      test_preds = model.predict(test_images)
      test_preds = tf.argmax(test_preds).numpy()
      print(test_preds)
      print(test_labels)
      acc = accuracy_score(test_preds,test_labels)
      print(acc)
      gen_accuracy.append(acc)
    return sum(gen_accuracy)/len(gen_accuracy)

In [ ]:
gen_accuracy = test_generalization(10)

[1 2 2]
[0. 1. 2.]
0.3333333333333333
[0 1 2]
[0. 1. 2.]
1.0
[0 0 2]
[0. 1. 2.]
0.6666666666666666
[0 1 0]
[0. 1. 2.]
0.6666666666666666
[0 1 2]
[0. 1. 2.]
1.0
[0 2 0]
[0. 1. 2.]
0.3333333333333333
[0 1 2]
[0. 1. 2.]
1.0
[0 1 2]
[0. 1. 2.]
1.0
[0 1 2]
[0. 1. 2.]
1.0
[0 1 2]
[0. 1. 2.]
1.0


In [ ]:
gen_accuracy

0.8